# Generated by Django 3.2.9 on 2022-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vagas',
            name='empresa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
