# Generated by Django 3.2.9 on 2022-01-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_vagas_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vagas',
            name='empresa',
            field=models.CharField(blank=True, default='Não preencher', max_length=50),
        ),
    ]
