# Generated by Django 3.2.9 on 2022-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_vagas_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField()),
                ('celular_1', models.CharField(blank=True, default='Se possuir preencher', max_length=12)),
                ('celular_2', models.CharField(blank=True, default='Se possuir preencher', max_length=12)),
                ('telefone', models.CharField(blank=True, default='Se possuir preencher', max_length=12)),
                ('logradouro', models.CharField(default='Endereço', max_length=50)),
                ('numero', models.CharField(default='Numero', max_length=5)),
                ('bairro', models.CharField(default='Bairro', max_length=20)),
                ('cidade_estado', models.CharField(default='Cidade/Estado', max_length=50)),
            ],
        ),
    ]
