# Generated by Django 3.2.9 on 2022-01-20 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_perfil_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil_empresa',
            name='bairro',
            field=models.CharField(default='Bairro', max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil_empresa',
            name='celular_1',
            field=models.CharField(blank=True, default='Se possuir preencher', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil_empresa',
            name='celular_2',
            field=models.CharField(blank=True, default='Se possuir preencher', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil_empresa',
            name='numero',
            field=models.CharField(default='Numero', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil_empresa',
            name='telefone',
            field=models.CharField(blank=True, default='Se possuir preencher', max_length=20),
        ),
    ]
