# Generated by Django 3.2.9 on 2022-01-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0005_auto_20220119_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil_empresa',
            name='data_abertura',
        ),
    ]
