# Generated by Django 3.2.9 on 2022-01-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidado', models.CharField(max_length=50)),
                ('data_nasc', models.DateField()),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=30)),
                ('cidade_c', models.CharField(max_length=30)),
                ('id_vagaa', models.CharField(max_length=10)),
            ],
        ),
    ]
