# Generated by Django 3.2.5 on 2022-01-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0002_candidatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil_jovem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nasc', models.DateField()),
                ('cel_1', models.CharField(blank=True, default='Se possuir preencher', max_length=20)),
                ('tel', models.CharField(blank=True, default='Se possuir preencher', max_length=20)),
                ('logradouro', models.CharField(default='Endereço', max_length=50)),
                ('numero', models.CharField(default='Numero', max_length=20)),
                ('bairro', models.CharField(default='Bairro', max_length=50)),
                ('cidade_estado', models.CharField(default='Cidade/Estado', max_length=50)),
            ],
        ),
    ]
