# Generated by Django 4.0.1 on 2022-01-23 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jovem', '0003_perfil_jovem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatar',
            name='id_vagaa',
            field=models.CharField(blank=True, default='Não é preciso preencher', max_length=10),
        ),
    ]
